### ISSUE TITLE
Desktop notifications

### ISSUE THREAD

**Issue by turbomaze** [techx/hackmit-dayof#5]
* add them when it's time for a new event
* site-wide; not just when they're on the homepage

**Comment by ehzhang** [comment]
IMO not worth. we have projection screens and all of the hackers work in the same space, so announcements are made there.

Push notifications (desktop or otherwise) are spammy and make the event feel worse.

**Comment by jenniferjzhang** [comment]
I think we should try to do them? I think it won't be that spammy if it was
just badging at the top corner of your window tab or if it was just a bar
on the top of the screen of the website.

*Jennifer J. Zhang*
(c) 214-534-8872 |  jjz@mit.edu

**Comment by ehzhang** [comment]
Weighing dev time vs actual value, I'm not sure that it's worth it.

Events don't always start at the correct time, and sometimes they move around. Something that does notifications for this needs to be flexible enough that we can push notifications to when we need them (socket subscription) and a console where only we can make updates.

As a rough thing, I suppose you can have an interval that keeps checking to see if there's an event going on, and then send a desktop notification if there is. 

But in any case, you'll effectively getting a notification badge at least once an hour. If I'm working at a hackathon, that's annoying enough for me to want to unsubscribe.

Having the most recent or current event highlighted as a schedule when checking the day of site seems worthy - but I *strongly* dislike the idea of pushing notifications. Notification fatigue is very real and using push should be handled delicately.

**Comment by jenniferjzhang** [comment]
That's fair. I'm for having a event highlight thing on the schedule. I
think thats what Anthony wanted to try doing too?

*Jennifer J. Zhang*
(c) 214-534-8872 |  jjz@mit.edu
